import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 'gau-admin',
    titleKey: 'projects.gau.title',
    descriptionKey: 'projects.gau.description',
    detailLeadKey: 'projects.gau.detailLead',
    roleKey: 'projects.gau.role',
    periodKey: 'projects.gau.period',
    companyUrl: 'https://digitalcenter.moscow/',
    technologies: [
      'Vue',
      'TypeScript',
      'Pinia',
      'Vue Router',
      'Vuetify',
      'Axios',
      'WebSocket',
      'SSE',
      'RBAC',
      'Markdown-it',
      'Mermaid',
      'LESS',
      'Vite',
    ],
    highlightsKeys: [
      'projects.gau.highlights.architecture',
      'projects.gau.highlights.realtime',
      'projects.gau.highlights.library',
      'projects.gau.highlights.markdown',
      'projects.gau.highlights.grouping',
      'projects.gau.highlights.api',
    ],
  },
  {
    id: 'gau-hr',
    titleKey: 'projects.gauHr.title',
    descriptionKey: 'projects.gauHr.description',
    detailLeadKey: 'projects.gauHr.detailLead',
    roleKey: 'projects.gauHr.role',
    periodKey: 'projects.gauHr.period',
    companyUrl: 'https://digitalcenter.moscow/',
    technologies: [
      'Vue',
      'TypeScript',
      'Pinia',
      'Vue Router',
      'Vuetify 4',
      'Axios',
      'RBAC',
      'Vite',
    ],
    highlightsKeys: [
      'projects.gauHr.highlights.migration',
      'projects.gauHr.highlights.registers',
      'projects.gauHr.highlights.ux',
      'projects.gauHr.highlights.rbac',
      'projects.gauHr.highlights.api',
      'projects.gauHr.highlights.shared',
    ],
  },
  {
    id: 'elros',
    titleKey: 'projects.elros.title',
    descriptionKey: 'projects.elros.description',
    detailLeadKey: 'projects.elros.detailLead',
    roleKey: 'projects.elros.role',
    periodKey: 'projects.elros.period',
    companyUrl: 'https://elros33.orgs.biz/',
    technologies: [
      'Vue',
      'Nuxt',
      'TypeScript',
      'Pinia',
      'Vuex',
      'Vuetify',
      'Axios',
      'RBAC',
      'Canvas API',
      'Chart.js',
      'CKEditor 5',
      'SCSS',
      'Vite',
    ],
    highlightsKeys: [
      'projects.elros.highlights.apps',
      'projects.elros.highlights.commerce',
      'projects.elros.highlights.payments',
      'projects.elros.highlights.canvas',
      'projects.elros.highlights.admin',
      'projects.elros.highlights.content',
    ],
  },
  {
    id: 'elros-taxi',
    titleKey: 'projects.elrosTaxi.title',
    descriptionKey: 'projects.elrosTaxi.description',
    detailLeadKey: 'projects.elrosTaxi.detailLead',
    roleKey: 'projects.elrosTaxi.role',
    periodKey: 'projects.elrosTaxi.period',
    companyUrl: 'https://elros33.orgs.biz/',
    technologies: [
      'Vue 2',
      'JavaScript',
      'Vuex',
      'Vue Router',
      'WebSocket',
      'JWT',
      'Canvas API',
      'DaData',
      'XLSX',
    ],
    highlightsKeys: [
      'projects.elrosTaxi.highlights.monolith',
      'projects.elrosTaxi.highlights.auth',
      'projects.elrosTaxi.highlights.realtime',
      'projects.elrosTaxi.highlights.orders',
      'projects.elrosTaxi.highlights.maps',
      'projects.elrosTaxi.highlights.ops',
    ],
  },
]

/** Поиск проекта по id для страницы /projects/[id] */
export function getProjectById(id: string): Project | undefined {
  return projects.find((project) => project.id === id)
}

/** Список id для prerender routes в nuxt.config (ru + /en/...) */
export const projectIds = projects.map((project) => project.id)
