import type { ExperienceItem } from './types'

export const experiences: ExperienceItem[] = [
  {
    id: 'gau',
    companyKey: 'experience.gau.company',
    roleKey: 'experience.gau.role',
    periodKey: 'experience.gau.period',
    locationKey: 'experience.gau.location',
    companyUrl: 'https://digitalcenter.moscow/',
    stack: [
      'Vue',
      'TypeScript',
      'Pinia',
      'Vue Router',
      'Vuetify',
      'Axios',
      'WebSocket',
      'SSE',
      'RBAC',
      'Markdown-it',
      'Mermaid',
      'LESS',
      'Vite',
    ],
    highlightsKeys: [
      'experience.gau.highlights.0',
      'experience.gau.highlights.1',
      'experience.gau.highlights.2',
      'experience.gau.highlights.3',
    ],
  },
  {
    id: 'elros',
    companyKey: 'experience.elros.company',
    roleKey: 'experience.elros.role',
    periodKey: 'experience.elros.period',
    locationKey: 'experience.elros.location',
    companyUrl: 'https://elros33.orgs.biz/',
    stack: [
      'Vue',
      'Nuxt',
      'TypeScript',
      'JavaScript',
      'Pinia',
      'Vuex',
      'Vuetify',
      'Axios',
      'RBAC',
      'Chart.js',
      'Canvas API',
      'CKEditor 5',
      'SCSS',
      'Vite',
    ],
    highlightsKeys: [
      'experience.elros.highlights.0',
      'experience.elros.highlights.1',
      'experience.elros.highlights.2',
      'experience.elros.highlights.3',
    ],
  },
]
